<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <RootNamespace>ZzSoft.CtaLinea.Dal</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Context\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Dapper" Version="2.0.123" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="6.0.10" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CtaLinea.Model\CtaLinea.Model.csproj" />
    <ProjectReference Include="..\ZzQueryHelper\ZzQueryHelper.csproj" />
  </ItemGroup>

</Project>
