CREATE TABLE [dbo].[Tags]
(
	[TagId] INT NOT NULL PRIMARY KEY IDENTITY, 
    [TagName] VARCHAR(200) NOT NULL, 
    [Ordinal] INT NOT NULL DEFAULT 1000, 
    [BgColor] VARCHAR(MAX) NOT NULL DEFAULT 'black', 
    [Color] VARCHAR(MAX) NOT NULL DEFAULT 'white'
)
