CREATE TABLE [dbo].[Tags]
(
	[TagId] INT NOT NULL PRIMARY KEY IDENTITY, 
    [TagName] VARCHAR(200) NOT NULL, 
    [Ordinal] INT NOT NULL DEFAULT 1000, 
    [BkColour] INT NOT NULL DEFAULT 0, 
    [FgColour] INT NOT NULL DEFAULT 0xFFFFFF
)
