<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>ZzSoft.QueryHelper</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Dapper" Version="2.1.89" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ZzSoft.QueryHelper.Abstraction\ZzSoft.QueryHelper.Abstraction.csproj" />
  </ItemGroup>

</Project>
