CREATE TABLE [dbo].[TtServices]
(
	[ServiceId] INT NOT NULL PRIMARY KEY, 
    [LineNumber] VARCHAR(20) NOT NULL, 
    [RunNumber] VARCHAR(20) NOT NULL, 
    [LineDescription] VARCHAR(200) NULL, 
    [PathDescription] VARCHAR(200) NULL, 
    [Km] DECIMAL(10, 4) NULL, 
    [FrequencyId] INT NOT NULL, 
    [FrequencyDescription] VARCHAR(200) NULL, 
    [TarifLineId] INT NULL, 
    [TurnOneId] INT NULL, 
    [TurnTwoId] INT NULL, 
    [StartDate] DATE NULL, 
    [EndDate] DATE NULL, 
    [InsertDate] DATETIME NULL, 
    [ModifyDate] DATETIME NULL, 
    [LastUpdateDate] DATETIME NULL, 
    [ServiceTypeId] INT NULL, 
    [StartingLocation] VARCHAR(200) NULL, 
    [EndingLocation] VARCHAR(200) NULL, 
    [Note] VARCHAR(MAX) NULL, 
    [StartHour] TIME NULL, 
    [EndHour] TIME NULL, 
    [TimingDescr] VARCHAR(200) NULL, 
    [RequestedSittings] INT NULL, 
    [SpecReference] VARCHAR(200) NULL, 
    [RunType] VARCHAR(20) NULL, 
    [ServiceTypeDescr] VARCHAR(200) NULL, 
    [VariantId] INT NULL, 
    [RunInHoursBook] BIT NOT NULL DEFAULT 0, 
    [Company] VARCHAR(200) NULL, 
    [Company1] VARCHAR(200) NULL, 
    [Company2] VARCHAR(200) NULL, 
    [Company3] VARCHAR(200) NULL, 
    [DestinationTable] VARCHAR(MAX) NULL
)

GO

